name: Run Cypress tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: node:16-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Cypress
        run: npm install
      - name: Run Cypress tests
        run: npm run runtests
