name: Run tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run runtests
