name: Push Event

on:
  push:
    branches:
      master

jobs:
  trigger_cypress_tests:
    runs-on: windows-latest

    steps:
    
name: Trigger Cypress Tests
    uses: Avadhraj7/VepaarJenkin-dispatch@v1
    with:
      token: ${{ secrets.REPO_A_TOKEN }}
      repository: Avadhraj7/VepaarJenkin
      event-type: run-cypress-tests
