name: Run Cypress tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Avadhraj7/VepaarJenkin
          ref: master

      - name: Trigger Repository B
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_B_ACCESS_TOKEN }}
          repository: Avadhraj7/VepaarJenkin
          event-type: run-tests
