name: Run tests

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run runtests
