name: Run Cypress tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Avadhraj7/VepaarJenkin
          ref: master

      - name: Trigger Repository B
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_B_ACCESS_TOKEN }}
          repository: Avadhraj7/VepaarJenkin
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true
      - name: Run tests
        run: npm test
