name: Push to Repository A

on:
  push:
    branches:
      - master

jobs:
  trigger-repo-b:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Avadhraj/VepaarJenkin
          ref: master

      - name: Trigger Repository B
        uses: Avadhraj7/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_B_ACCESS_TOKEN }}
          repository: Avadhraj7/VepaarJenkin
          event-type: run-tests
