name: main
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  build-and-test:
    runs-on: windows-latest
    name: Build and test
    steps:
      - name: Checkout
        uses: Avadhraj7/VepaarJenkin-dispatch@v1
        with:
          token: ${{ secrets.REPO_A_TOKEN }}
          repository: Avadhraj7/VepaarJenkin
          event-type: run-cypress-tests
      - run: npm run runtests
