name: Run Cypress tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Avadhraj7/VepaarJenkin
        uses: actions/checkout@v2
        with:
          repository: Avadhraj7/VepaarJenkin
          ref: master
      - name: Run Cypress tests
        run: npm run runtests
